name = "LogitSamplers"
uuid = "1b30fcfc-0ee9-4be2-9cfe-b2289b43e041"
authors = ["Ben Murrell <murrellb@gmail.com>", "Anton Oresten <antonoresten@gmail.com>"]
version = "0.2.0"

[deps]
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
NNlib = "0.9"
Random = "1"
Statistics = "1"
julia = "1.9"
